version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: swipex_db_container
    restart: always
    environment:
      POSTGRES_USER: swipex_user
      POSTGRES_PASSWORD: Dileep100
      POSTGRES_DB: swipex_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: swipex_backend_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://swipex_user:Dileep100@db:5432/swipex_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: swipex_frontend_container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
